---
version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-txn-logs:/var/lib/zookeeper/log

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  
  init-topics:
    build:
      context: init-topics
    container_name: init-topics
    depends_on:
      - broker
    volumes:
      - ./create-topics.py:/tmp/topics/create-topics.py
      - ./topics.yml:/tmp/topics/topics.yml
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                  cub kafka-ready -b broker:29092 1 20 && \
                  python3 /tmp/topics/create-topics.py -f /tmp/topics/topics.yml -b broker:29092'"

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8080:8080"
    depends_on: 
      - broker
    environment:
      AKHQ_CONFIGURATION: |-
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "broker:29092"

volumes:
  zk-data:
  zk-txn-logs:
  kafka-data: